### ISSUE TITLE
Syrupy assertion diff does not show missing carriage return

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#116]
**Describe the bug**

Syrupy assertion diff does not show missing carriage return.

**To Reproduce**

Add this test.

```python
def test_example(snapshot):
    assert snapshot == "line 1\r\nline 2"
```

Run `pytest --snapshot-update`.

Remove the `\r` from the string in the test case so you get:

```python
def test_example(snapshot):
    assert snapshot == "line 1\nline 2"
```

Run `pytest`. The test will fail with a useless diff of "...".

**Expected behavior**

Syrupy should output each line with the missing carriage return, with some indication of what's missing.

**Additional context**

Syrupy v0.3.1

#113 fixed the bug where carriage returns were not being serialized. This issue addresses the missing functionality in the snapshot assertion diff reporter.

**Comment by iamogbz** [comment]
@noahnu should this have been closed? What is left in this?

**Comment by noahnu** [comment]
@iamogbz It still does not show the missing character. The linked PR #120 shows a symbol for CR and NL if it detects the change is relevant to show in a diff. Haven't had time yet to finish off that PR though.  -- It was a bit of a refactor of the diff reporting, and I think it might still have some bugs. Feel free to checkout the branch and give it a try though.
