### ISSUE TITLE
Account for accessibility and readability in snapshot outputs

### ISSUE THREAD

**Issue by msrose** [tophat/syrupy#120]
This is a general issue to track notes about readability and accessibility in diffs. See this jest blog post for more information: https://jestjs.io/blog/2020/01/21/jest-25, and this jest PR https://github.com/facebook/jest/pull/9132

They seem to have put a lot of effort into improving diff outputs recently so it's definitely something to consider and take inspiration from.

Sorry for the lack of specificity on this issue, mostly created it for tracking purposes with the idea of triggering an investigation.

**Comment by noahnu** [comment]
Currently we use _green_ for the content from the snapshot (expected) and _red_ for mismatches (received). The colours are provided by the [colored](https://pypi.org/project/colored/) package.

<details>
<summary>256 Colors Foreground (Text) Table from colored (https://pypi.org/project/colored/) </summary>

![image](https://user-images.githubusercontent.com/1297096/73707766-6d575700-46ca-11ea-9b47-73a0306a7b1a.png)

</details>

In the above chart, Red = 1 and Green = 2.

I'm definitely in favour of making syrupy more accessible.

**Comment by noahnu** [comment]
Addressing this alongside #116 in https://github.com/tophat/syrupy/pull/126

**Comment by iamogbz** [comment]
Possible issue with the colors https://github.com/facebook/jest/issues/9459 cc @noahnu
