### ISSUE TITLE
Replacing `os.path` with `pathlib`

### ISSUE THREAD

**Issue by mcataford** [tophat/syrupy#121]
**Is your feature request related to a problem? Please describe.**
This is mainly a refactor concern: in Python 3.4+, [`pathlib`](https://docs.python.org/3/library/pathlib.html) can serve as a more powerful (and built-in) replacement for `os.path`, dealing with flexible pathlike objects compatible anywhere where a string path may be used. It offers extra features over just dealing with paths, such as navigating filetrees with ease using object methods. Succinctly put, it provides a cleaner experience when dealing with file structures.

**Describe the solution you'd like**
Refactor `syrupy` so that it uses `pathlib` wherever it deals with paths instead of `os.path`.

**Describe alternatives you've considered**
Continuing with `os.path` and accepting increased complexity.

**Additional context**
Since Syrupy already requires `python >= 3.6`, the version requirement for `pathlib` isn't a concern.

**Comment by mcataford** [comment]
(Interested in taking this on, btw.)

**Comment by noahnu** [comment]
I'm in favour of this. Feel free to take this on.
