### ISSUE TITLE
Fail when there are unused snapshots

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#13]
**Is your feature request related to a problem? Please describe.**

When there are unused snapshots there should be a behaviour to fail the tests especially for running in ci.

**Describe the solution you'd like**

Fail when unused snapshots are detected.

**Describe alternatives you've considered**

Flag to fail in ci `--ci`.

**Additional context**

**Comment by noahnu** [comment]
I'd be in favour of having the plugin be "strict" by default and allow users to opt-out via some config or cli flags.

**Comment by noahnu** [comment]
How would you fail? / How would the failure be reported? This would happen outside of individual test cases

**Comment by noahnu** [comment]
Addresses https://github.com/syrusakbary/snapshottest/issues/73
