### ISSUE TITLE
Unused snapshots reported for deselected tests

### ISSUE THREAD

**Issue by msrose** [tophat/syrupy#134]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3495264/75563052-a5c32a00-5a17-11ea-8404-c179f5b6b860.png)
Notice how in the screenshot that 5/6 tests are deselected, but the test run reports 2 unused snapshots.

**To Reproduce**
1. `pip install pytest pytest-watch syrupy`
1. Add this test file:
    ```python
    import pytest

    def test_thing_1(snapshot):
        assert snapshot == "123"

    def test_thing_2(snapshot):
        assert snapshot == "456"

    def test_thing_11(snapshot):
        assert snapshot == "123"

    def test_thing_22(snapshot):
        assert snapshot == "456"

    @pytest.mark.wip
    def test_thing_111(snapshot):
        assert snapshot == "123"

    def test_thing_222(snapshot):
        assert snapshot == "456"
    ```
1. Run `pytest --snapshot-update`
1. Run `ptw -- -m wip` to watch test files and only run tests with the `wip` mark
1. The pytest run reports 2 unused snapshots
1. It seems like this behaviour is the same without using ptw, e.g. running `pytest -m wip` reports two unused snapshots.

**Expected behavior**
Here I'd expect no unused snapshots to be reported -- seems like deselected tests are sometimes being considered not having used their snapshot, which is technically true, but given that the test didn't run I'd say there's no way to assess whether or not the snapshot is out of date.

**Screenshots**
Included above

**Desktop (please complete the following information):**
 - MacOS 10.14.5 with python 3.6.2 and syrupy 0.3.2

**Additional context**
The behaviour doesn't occur with two tests, i.e. the following test file does report an unused snapshot when run with `pytest -m wip`:
```python
import pytest

def test_thing_1(snapshot):
    assert snapshot == "123"

@pytest.mark.wip
def test_thing_2(snapshot):
    assert snapshot == "456"
```

**Comment by noahnu** [comment]
Odd this wasn't fixed in https://github.com/tophat/syrupy/pull/127 (cc @iamogbz )

**Comment by msrose** [comment]
Discovered after more testing: it's something to do with similarities in test names, if the test file is changed so that the test names don't share prefixes, it works fine:

These tests behave as expected when running `pytest -m wip`

```python
import pytest

def test_thing_1(snapshot):
    assert snapshot == "123"

def test_thing_3(snapshot):
    assert snapshot == "123"

def test_thing_5(snapshot):
    assert snapshot == "123"

def test_thing_7(snapshot):
    assert snapshot == "123"

def test_thing_10(snapshot):
    assert snapshot == "123"

@pytest.mark.wip
def test_thing_2(snapshot):
    assert snapshot == "456"
```
