### ISSUE TITLE
Clarify test methods for integration tests and testing in general

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#137]
Current tests are starting to be hard to reason about. Some clarification about the behaviour each test is attempting to verify is getting more essential.

**Describe the solution you'd like**

Make each test case group a single file testing all the behaviours with module and test doc string explaining the purpose

**Describe alternatives you've considered**
N/A

**Additional context**
The [`tests/test_integration_default.py`](https://github.com/tophat/syrupy/blob/3e46a842ddfde309e46830918d380da5da2c04b8/tests/test_integration_default.py) file is an example of this complexity.

**Comment by iamogbz** [comment]
@noahnu how about naming files based on what they test and splitting off when each file testing scope gets too large
```sh
tests/
  integration/
    test_snapshot_option_default_extension.py
    test_snapshot_option_no_colors.py
    test_snapshot_option_update.py
    test_snapshot_option_warn_unused.py
    utils.py # containing stuff like "find_snapshot_summary_in_result"
  unit/
    extensions/
      amber/
        test_amber_filters.py # with use of filters
        test_amber_matchers.py # with use of matchers
        test_amber_serializer.py # containing the different data types supported and parametrized
      image/
        test_image_png.py
        test_image_svg.py
      test_base.py
      test_single_file.py
    test_data.py
    test_location.py
    test_report.py
    test_session.py
    test_utils.py
```

**Comment by noahnu** [comment]
Yeah that looks good :+1:
