### ISSUE TITLE
Shared test mixins that use the snapshot fixture save under wrong name

### ISSUE THREAD

**Issue by lime-green** [tophat/syrupy#195]
**Describe the bug**
Shared test mixins that use the snapshot fixture save under the mixin class name rather than the subclass name

**To Reproduce**
```py
class SharedMixin:
    def test_math(self, snapshot):
        assert 1 + 1 == snapshot

class TestMathWorks(SharedMixin):
    pass

class TestMathWorksAgain(SharedMixin):
    pass
```

**Expected behavior**
The snapshot is saved under the subclass names

**Comment by noahnu** [comment]
Currently looking at this, however the specific example you provided might be better served by parametrization? See: https://docs.pytest.org/en/latest/fixture.html#fixture-parametrize
