### ISSUE TITLE
Compare snapshots without deserializing

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#21]
**Is your feature request related to a problem? Please describe.**

Snapshots are currently deserialized into python objects before comparison is done, this is unnecessary

**Describe the solution you'd like**

No deserialization is done and comparison is done on the serialized representation

**Describe alternatives you've considered**

N/A

**Additional context**

Unlocks using `yaml.dumps` in place of `yaml.safe_dumps` because loading yaml data is needless

**Comment by iamogbz** [comment]
It was never properly fixed and then subsequently reverted in #30

**Comment by noahnu** [comment]
For the tank serializer, can we grab test names out of the file without using unsafe tank loader?
