### ISSUE TITLE
A "no formatting" mode for CI runs which don't support text formatting

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#218]
**Is your feature request related to a problem? Please describe.**

Snapshot failures in my Jenkins runs show the colour codes which make it hard to read the diffs.

![image](https://user-images.githubusercontent.com/1297096/81453860-a2a39300-9158-11ea-9888-dfc066d5c070.png)

**Describe the solution you'd like**

An opt-in `--no-formatting` (`--no-colors`) mode.

**Describe alternatives you've considered**

Using a better CI runner.

**Additional context**

jest has a `--no-colors` mode.

**Comment by iamogbz** [comment]
I wonder if [`colored`](https://pypi.org/project/colored/) has support for this out of the box. There's a lot of use for env variables like [`NO_COLOR`](https://no-color.org/) and [`ANSI_COLORS_DISABLED`](https://www.google.com/search?q=ANSI_COLORS_DISABLED).

Example in alternative python library [`termcolor`](https://pypi.org/project/termcolor/)
https://github.com/hfeeki/termcolor/blob/master/termcolor.py#L107
