### ISSUE TITLE
Pretty diff of snapshot comparisons

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#22]
**Is your feature request related to a problem? Please describe.**

Diffing complex objects on assertion failure does not show only the change but the entire snapshot

**Describe the solution you'd like**

Should show the exact line and characters (tokens) that differ between snapshots

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by noahnu** [comment]
This should be done on the same raw string that's written to the file system, however we should also support custom types. E.g. how to pretty diff images via the image serializer plugin?

**Comment by noahnu** [comment]
Only thing we're missing here is showing exact characters within a line. Should we only do this for single line diffs? I imagine it might be too verbose in the general case.
