### ISSUE TITLE
Python version in setup.py is outdated

### ISSUE THREAD

**Issue by arturbalabanov** [tophat/syrupy#238]
**Describe the bug**

#140 suggests that the projects supports Python 3.8.1, however the Python version specifier is `~3.6` which is equivalent of `>=3.6.0 <3.7.0`.

**To Reproduce**

When trying to install the package with poetry (`poetry add syrupy`) I get:

```
[...]

The current project's Python requirement (>=3.6) is not compatible with some of the required packages Python requirement:
  - syrupy requires Python ~=3.6

Because no versions of syrupy match >0.4.2,<0.5.0
 and syrupy (0.4.2) requires Python ~=3.6, syrupy is forbidden.

[...]
```

As shown in the error message in `pyproject.toml` I have `python = ">=3.6"`.

**Expected behavior**

The package should install since `syrupy` supports all Python versions over 3.6

**Comment by noahnu** [comment]
@arturbalabanov Thanks for raising this issue! Would you like to put up a PR to fix this? Otherwise I'll get this fixed today

**Comment by noahnu** [comment]
Fixed in https://github.com/tophat/syrupy/releases/tag/v0.4.3
