### ISSUE TITLE
Syrupy crashes when used with pytest-flake8

### ISSUE THREAD

**Issue by daphtdazz** [tophat/syrupy#246]
## Bug description

With the following dependencies in my poetry file:

```py
syrupy = "^0.4.3"
pytest = "^5.4.2"
pytest-flake8 = "^1.0.6"
```

I have this test file:

test_snapshot.py
```py
def test_a_snapshot(snapshot):
    assert 1 == snapshot
```

And when I run it I get:

```
$ py.test --flake8 test_snapshot.py 
============================= test session starts =============================
... blah ...                            

test_snapshot.py::FLAKE8 PASSED                                         [ 50%]
test_snapshot.py::test_a_snapshot PASSED                                [100%]
Traceback (most recent call last):
...
  File "/path/to/venv/lib/python3.7/site-packages/syrupy/report.py", line 104, in <genexpr>
    for node in self.ran_items
  File "/path/to/venv/lib/python3.7/site-packages/syrupy/location.py", line 13, in __init__
    self.modulename = self._node.obj.__module__
AttributeError: 'Flake8Item' object has no attribute 'obj'
```

## To Reproduce
1. Install pytest-flake8 and syrupy
2. Write a test in a test file that uses snapshot
3. run `py.test --flake8 path/to/your/test.py`

## Expected behaviour
The test should not fail in tear down and py.test should exit with 0 exit code.

## Screenshots
N/A

## Environment
 - OS: macOS 10.15.3 Catalina
 - Python Version 3.7.4

## Extra info

FWIW I "fixed" this for my install by using the following monkey-patch:

```py
# Monkey patch Flake8Item due to a conflict with syrupy https://github.com/tophat/syrupy/issues/246
import pytest_flake8
pytest_flake8.Flake8Item.obj = type('DummyFlake8Obj', (), {})
```

But I think it's really a problem with syrupy for assuming the `obj` attribute will be on the pytest `Item`.

**Comment by noahnu** [comment]
Thanks for opening this issue. I'll take a look today

**Comment by noahnu** [comment]
Looking into pytest-flake8, it seems like an interesting use of pytest.

In the pytest source, they don't assume node's always have an obj: https://github.com/pytest-dev/pytest/blob/2f406bb9cb8538e5a43551d6eeffe2be80bccefa/src/_pytest/nodes.py#L412.

Either way, I put up a PR with a fix. Just investigating how we could test for this.
