### ISSUE TITLE
Add support for other python test runners

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#257]
**Is your feature request related to a problem? Please describe.**

Other popular python test runners e.g. `nose`, `unittest`, `django`

**Describe the solution you'd like**

And plugins and/or mixins

**Describe alternatives you've considered**

Only support `pytest`

**Additional context**
- [snapshottest](https://github.com/syrusakbary/snapshottest)

**Comment by noahnu** [comment]
Pros:
- No reason to use snapshottest anymore.

Cons:
- Increased complexity from handling more ways to use syrupy. More edge cases to consider.
- More complex CI. We'll need to install pytest, run tests, then remove pytest. Or use a matrix setup, but either way increase complexity of CI runs.
- The abstraction is already mostly decoupled from pytest, but there are a few remaining points. We even import pytest for the types in a few places. I think there is such a thing as too much abstraction. Unless we pause to re-examine the code structure, it can become quite complicated, discouraging new contributors and making it harder to maintain.

---

pytest supports running unittest, so in that case I'd recommend projects to switch to pytest.

What's the motivation for supporting other test runners?

**Comment by noahnu** [comment]
Started taking a bit of a look at the feasability of this -- though even if I get something working, not sure I'd want to merge it.

Current idea:
- Refactor the code to isolate the pytest import to a single file (did this quite easily in a local branch).
- Rely on a "--snapshot-runner-mode" CLI flag to skip the pytest import and replace the `@pytest.fixture` with a noop.
- Expose a UnitTest class that directly invokes the pytest hooks. For this we'd have to construct our own session/config/terminalreporter.

**Comment by noahnu** [comment]
This adds to much unnecessary complexity.
