### ISSUE TITLE
Syrupy reports snapshot failure for expected assertion errors

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#292]
**Describe the bug**

Snapshot reports snapshot as failed even when it was expected to

**To Reproduce**
1. Add test file `test_file.py` with content
```py
import pytest
def test_expected_fail(snapshot):
    with pytest.raises(AssertionError):
        assert "Does not exist" == snapshot
```
2. `pytest test_file.py`
3. Completes successfully with report saying test failed

**Expected behavior**

Snapshot should not be counted towards failures

**Screenshots**

<img width="1084" alt="Screen Shot 2020-07-12 at 9 36 38 AM" src="https://user-images.githubusercontent.com/2528959/87247668-3a588280-c423-11ea-9590-89ed223a46a5.png">

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by noahnu** [comment]
This seems like a strange edge case, wouldn't the preferred approach being `!=` which we also don't support?

**Comment by iamogbz** [comment]
@noahnu we do use it here https://github.com/tophat/syrupy/blob/83ded3c73917673fcb46857eb291e26704c2c0f6/tests/test_matchers.py#L45-L46
Not sure there's a usecase for `!=`

**Comment by noahnu** [comment]
The more serious issue is that syrupy reports a snapshot failure but does not fail the test suite in this case.

**Comment by iamogbz** [comment]
What would your expected behaviour be?

**Comment by noahnu** [comment]
Identical behaviour to:

```python
def test_case():
    def throw():
        raise Exception()

    with pytest.raises(Exception):
        assert 1 == throw()
```

The above test passes because when the exception is thrown the control flow interrupted and the assertion is never made.

With

```python
 with pytest.raises(PathTypeError, match="does not match any of the expected"): 
     assert actual == snapshot(matcher=path_type(**kwargs)) 
```

The exception should be caught and the test successful. The assertion should not be counted. So the snapshot is not included in the success or failure count at all.

We can also throw an exception if someone tries: `assert ... != snapshot()` as not supported with a disclaimer in the README to not try to catch a snapshot assertion error.

**Comment by noahnu** [comment]
I'm starting to question whether this is an actual problem/bug. Users should not be writing tests that assert a snapshot fails. It just happens we need to assert this to test syrupy itself.

I'd vote to close this as Won't Fix. Unless @iamogbz you have other thoughts?
