### ISSUE TITLE
Make pyyaml dependency optional

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#38]
**Is your feature request related to a problem? Please describe.**

Syrupy supports multiple serializes including custom serializes. If a codebase using syrupy selects a non-yaml serializes, there is no reason to install the unused dependency.

**Describe the solution you'd like**

List pyyaml as an optional dependency. Throw error if the seralizer is used if pyyaml is not present in system.

**Describe alternatives you've considered**

- Continue installing unused dependencies.

**Additional context**

Python dependency management is awful :smile:

**Comment by iamogbz** [comment]
Closed by #69
