### ISSUE TITLE
Automate releases on GitHub

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#43]
**Is your feature request related to a problem? Please describe.**

Package releases are currently manual. We should automate these releases via semantic commits.

This means we need to enforce semantic commits as part of precommit hook and CI, and parse the commits to determine version bump.

**Alternatives**

Continuing manual releases w/ thoroughly documented process.

**Comment by iamogbz** [comment]
### Relevant links

- [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [commitizen](https://pypi.org/project/commitizen/)
- [lint git commit](http://jorisroovers.com/gitlint/configuration/)
