### ISSUE TITLE
KeyError during report generation in syrupy when pytest is also doing doctests

### ISSUE THREAD

**Issue by daphtdazz** [tophat/syrupy#451]
**Describe the bug**

Errors such as 

```
735    PyTestLocation(item).matches_snapshot_name(snapshot_name)
736  File "/app/.venv/lib64/python3.6/site-packages/syrupy/report.py", line 171, in <genexpr>
737    if self.selected_items[nodeid]
738 KeyError: 'path/to/doctest.py::path.to.doctest.MyClass.doctest'
```

**To reproduce**

Will try and provide for a test, but I will push a patch shortly since I know what the issue is. It also doesn't seem to be deterministic because it depends on ordering in a `set` object (I think).

**Expected behavior**

Not to crash during report generation.

**Screenshots**

N/A

**Environment (please complete the following information):**

- OS: Mac OSX Catalina
- Syrupy Version: 1.1.0
- Python Version: 3.7

**Additional context**

**Comment by daphtdazz** [comment]
Incidentally I'm pretty sure this was introduced by [this fix](https://github.com/tophat/syrupy/commit/8ed194cc9e7365c6c4fbd9fcd45d403646334b18) for [my previous issue](https://github.com/tophat/syrupy/issues/246)!

**Comment by daphtdazz** [comment]
The patch that I'm doing locally (and I will push an MR soon, but maybe not today...) is:

```
from syrupy.session import SnapshotSession


real_ran_item = SnapshotSession.ran_item

def patched_ran_item(self, nodeid):
    # Issue
    if nodeid not in self._selected_items:
        return
    real_ran_item(self, nodeid)

SnapshotSession.ran_item = patched_ran_item
```

The problem is that `SnapshotSession.filter_valid_items()` was called when setting `_selected_items` but then we update `_selected_items` in `SnapshotReport.ran_items()`, without checking whether we were supposed to have selected it.

**Comment by noahnu** [comment]
@daphtdazz Is this still an issue?

**Comment by daphtdazz** [comment]
Sorry for delay, yes it still is in 1.3.1.
