### ISSUE TITLE
Report which snapshots are unused

### ISSUE THREAD

**Issue by eaculb** [tophat/syrupy#465]
**Is your feature request related to a problem? Please describe.**

In test suites that are very long, it can be tedious and frustrating to try to find which snapshots are stale/unused after eg many tests are changed. The current report lists how many snapshots were unused, but not which ones. 

**Describe the solution you'd like**

I would like an optional flag that, when provided, will include the locations & names of unused snapshots in the final report.

**Describe alternatives you've considered**

I don't think there's a great alternative. Usually to find out which snapshots have become obsolete, I have to provide the `--snapshot-update` option and look at the generated diff. When syrupy is running as a CI step, this means I have to rerun the test suite locally, which can be very time consuming.

**Additional context**

I would be happy to make a PR to address this issue.

**Comment by noahnu** [comment]
Thank you for opening the feature request!

Perhaps `--snapshot-details` or something of that sort for a detailed report including file paths?

Feel free to put up a PR. This is the code you'll need to modify, the "lines" of the SnapshotReport: https://github.com/tophat/syrupy/blob/818d405a85c2f1f5db9d673e632677c10cb52ad9/src/syrupy/report.py#L223. Currently we print `num_unused`, however we also have more detailed information in `unused`.

If you have any questions, you can always post in this issue, or join us on our discord: https://discord.gg/YhK3GFcZrk
