### ISSUE TITLE
updating a single snapshot will delete other snapshots

### ISSUE THREAD

**Issue by xareelee** [tophat/syrupy#518]
**Describe the bug**

I want to run and update only one test snapshot, but it delete other snapshot files in the same `__snapshots__` directory.

```shell
# This will delete other snapshots files in `tests/__snapshots__/`
$ pytest --snapshot-update tests/test_something.py   

```

**Expected behavior**

It should only update the specified snapshot file.

**Environment (please complete the following information):**

- OS: Mac OSX 11.3.1
- Syrupy Version: 1.2.3
- Python Version: 3.7.10

**Comment by noahnu** [comment]
@iamogbz Is this a regression from the pytest argument refactor recently?

**Comment by iamogbz** [comment]
This had to do with the order of arguments not being handled correctly I believe bug introduced in `v0. I 8.2`(https://github.com/tophat/syrupy/releases/tag/v0.8.2). Should be fixed by [`v1.2.4`](https://github.com/tophat/syrupy/releases/tag/v1.2.4), at least could not reproduce there.

**Comment by noahnu** [comment]
@xareelee Let me know if 1.2.4 fixes it for you.

**Comment by xareelee** [comment]
@noahnu @iamogbz 
I tried both `1.2.4` and `1.3.0`, they work well. Thanks.
