### ISSUE TITLE
Hide snapshot report summary if there is nothing to report

### ISSUE THREAD

**Issue by RobertCraigie** [tophat/syrupy#534]
**Is your feature request related to a problem? Please describe.**

No point in outputting a summary when there is nothing to report

**Describe the solution you'd like**

Patched this myself by modifying the `pytest_terminal_summary` hook to the following,
will happily make a PR if this is wanted.

```py
with __terminal_color(config):
    lines = terminalreporter.config._syrupy.report.lines
    first = next(lines)
    if first:
        terminalreporter.write_sep("-", gettext("snapshot report summary"))
        terminalreporter.write_line(first)
        for line in lines:
            terminalreporter.write_line(line)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by noahnu** [comment]
Is this in the case when you don't have any snapshots, or just no failures? If it's latter, I find it useful be informed on success since it gives me confidence things are working.

**Comment by RobertCraigie** [comment]
@noahnu sorry, I should've clarified that, just when there's no snapshots. I agree that it's useful to report on success.
