### ISSUE TITLE
Add extension for JSON snapshots

### ISSUE THREAD

**Issue by fbjorn** [tophat/syrupy#551]
**Is your feature request related to a problem? Please describe.**

Usually I use snapshots when testing REST APIs. It's quite convenient to not compare response to a long dictionary, but rather check status code and that response is aligned with a snapshot. Quite often responses are JSON compatible. Therefore I would like to have in `syrupy` an extension supporting that.

**Describe the solution you'd like**

```python
from datetime import datetime
 
import pytest

from syrupy.extensions.json import JSONSnapshotExtension
from syrupy.matchers import path_name_str

@pytest.fixture
def snapshot_json(snapshot):
    return snapshot.use_extension(JSONSnapshotExtension) 


def test_api_call(client, snapshot_json):
    resp = client.post("/endpoint")
    assert resp.status_code == 200
    assert snapshot_json == resp.json()


def test_create_user(client, snapshot_json):
    resp = client.post("/user", json={"name": "Jane"})
    assert resp.status_code == 201

    matcher = path_name_str({
      "id": (int,),
      "registeredAt": (datetime,)
    })
    assert snapshot_json(matcher=matcher) == resp.json()
```

Following tests should create `<test_name>.json` snapshots with following content:
```json
{
  "foo": "bar"
}
```

and in case of dynamic data:

```json
{
  "id": "<INT>",
  "registeredAt": "<DATETIME>",
  "name": "Jane"
}
```

**Describe alternatives you've considered**

If you have some concerns about having this bundled into `syrupy`, then I could create my own extension library, but to be honest I think the scenario I described is quite common, so I would appreciate it to be available in syrupy out of the box.

**Additional context**

Probably I should have created this FR before rushing to implementation, but there's a PR ready. I would consider it as a draft, and would appreciate to hear any feedback cause I might have missed something conceptually-wise. On the other hand, I mostly copy-pasted this extension from my current project, where it's already used and it works pretty good

**Motivation**

Theoretically, I can just use default Amber extension, but I don't like the format of it in this case. When your JSON response is a `.json` file, then you have nicer diffs, nicer syntax highlighting in your code editor, and most importantly, it's easier to just look into them

**Comment by noahnu** [comment]
I'm a bit swamped this week, but will take a look at your PR first thing next week. Overall, adding a native JSON extensions sounds okay to me.

**Comment by noahnu** [comment]
https://github.com/tophat/syrupy/releases/tag/v1.7.0

**Comment by dtczest** [comment]
Looks like the readme.md based on changes from this issue gives incorrect instructions, btw. path_name_str doesn't appear to have been implemented yet.

**Comment by noahnu** [comment]
Updated the README

**Comment by dtczest** [comment]
Thanks! I've submitted a bug for this when used with older versions of Python: https://github.com/tophat/syrupy/issues/585
