### ISSUE TITLE
Give custom name to image snapshot file

### ISSUE THREAD

**Issue by bendidi** [tophat/syrupy#555]
Hello I have some tests where I need to generate multiple snapshot images in the same test.

Is it possible to provide the target snapshot name file to `snapshot` when asserting the images are equal ?

My use case:

```py
from syrupy.extensions.image import PNGImageSnapshotExtension
import base64
import pytest


@pytest.fixture
def snapshot(snapshot):
    return snapshot.use_extension(PNGImageSnapshotExtension)

def test_some_func(snasphot):
   base64_img1, base64_img2 = func()

    assert base64.base64decode(base64_img1) == snapshot
    assert base64.base64decode(base64_img2) == snapshot
```

It works as intended, but IMO the syntax is weird and magical, (we are basically testing 2 different things against the same object).

what I'm looking for / propose is to be able to set a custom filename for the snapshot if we want:

```py
    assert base64.base64decode(base64_img1) == snapshot(filename="photo_image.png")
    assert base64.base64decode(base64_img2) == snapshot(filename="signature_image.png")
```

Thanks!

**Comment by danfrankcb** [comment]
+1 for this feature. We have snapshots within a single unit test that need to land in named files. As soon as that lands we'll migrate off of snapshottest :)

**Comment by noahnu** [comment]
@danfrankj would the behaviour of overriding num_call as @bendidi suggested be sufficient? I don't think we could easily full control of the name (outside of a custom extension) due to challenges with snapshot discovery.

**Comment by noahnu** [comment]
@iamogbz Looks like this github comment was posted by the dry run for the next branch ^.
