### ISSUE TITLE
How to implement assertions with a tolerance

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#565]
### Discussed in https://github.com/tophat/syrupy/discussions/537

<div type='discussions-op-text'>

<sup>Originally posted by **rassie** August  4, 2021</sup>
I would like to implement this assertion to check that `count` is within 10% of the expected value:

```python
assert count <= snapshot * 1.1 and count >= snapshot * 0.9
```

Is there a good way to do that with `syrupy`?</div>

**Comment by filosfino** [comment]
checkout https://github.com/inveniosoftware/dictdiffer
