### ISSUE TITLE
Abstract the snapshot assert equal in extensions

### ISSUE THREAD

**Issue by obendidi** [tophat/syrupy#574]
**Is your feature request related to a problem? Please describe.**

Hello, I'm not sure if it's a good idea, but how about abstracting the assert equal done in the base snapshot class to be performed instead by the extension ?

https://github.com/tophat/syrupy/blob/ee8edaacc940c0f16fb86319ca4d7f7429f8f82d/src/syrupy/assertion.py#L192

**Describe the solution you'd like**

Ideally we could have something like this:

```py
# syrupy/asserstion.py
        try:
            snapshot_data = self._recall_data()
            serialized_data = self._serialize(data)
            matches = snapshot_data is not None and self.extension.is_equal(serialized_data, snapshot_data)
            assertion_success = matches
            if not matches and self._update_snapshots:
                self.extension.write_snapshot(
                    data=serialized_data,
                    index=self.index,
                )
                assertion_success = True
            return assertion_success
        except Exception as e:
            assertion_exception = e
            return False
```

and then the in the base extension:

```py
class SnapshotFossilizer(ABC):
    # can maybe also be a class method, or do a lot of refactors ...
    def is_equal(self, serialized_data, snapshot_data):
          return serialized_data == snapshot_data
```

**Additional context**

The context is I was trying to create an extension to save snapshots of pandas dataframes as csv files (or some other format^^), probably not the best idea since a dataframe can be converted to dict and snapshoted the classical way ... but why not :grin: .

And for that I wanted to use [pd.DataFrame.equals()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.equals.html) to compare between the 2 dataframes

**Comment by noahnu** [comment]
https://github.com/tophat/syrupy/pull/548

**Comment by iamogbz** [comment]
Should be addressed by the above PR[548]
