### ISSUE TITLE
SerializerClass vs IOClass

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#59]
## Discussion

Would it be more idiomatic to have the current `SerializerClass` be replaced in name by `IOClass` but retain the same functionality.

### Arguments

| For replacing with `AbstractSnapshotIO` | For keeping `Serializer` nomenclature |
| --- | --- |
| IO handles the file system, the serialization is just a step in the process | Serializer handles writing and reading from file system |
| IO (input, output) is more encompassing allowing for extensions to functionality like preparing assertion diffs | Serializer is a more familiar concept to most people making the naming appropriate for its function

### [Example](https://github.com/tophat/syrupy/compare/7cde8a7...feat-22)

https://github.com/tophat/syrupy/blob/44b0f6ccdc1036c531a76dfac87ed5ca75d6be51/README.md#L71
https://github.com/tophat/syrupy/blob/44b0f6ccdc1036c531a76dfac87ed5ca75d6be51/src/syrupy/__init__.py#L66-L71
https://github.com/tophat/syrupy/blob/44b0f6ccdc1036c531a76dfac87ed5ca75d6be51/src/syrupy/assertion.py#L71-L75
https://github.com/tophat/syrupy/blob/44b0f6ccdc1036c531a76dfac87ed5ca75d6be51/src/syrupy/assertion.py#L135-L138

**Comment by noahnu** [comment]
> IO (input, output) is more encompassing allowing for extensions to functionality like preparing assertion diffs

I'm not sure "IO" encompasses assertion behaviour. I think "serialization" can contain IO:

> serialization (or serialisation) is the process of translating data structures or object state into a format that can be stored
> ...
> A method of storing data (in databases, on hard disk drives).
>
> &mdash; https://en.wikipedia.org/wiki/Serialization

**Comment by iamogbz** [comment]
> I'm not sure "IO" encompasses assertion behaviour

I was using the example of the showing the difference between two serialized data strings, which can be used to replace the current

**Comment by noahnu** [comment]
Some other options: SnapshotPlugin, Extensions, IOSerializer.

Are there any other projects that have a similar pattern that we can take inspiration from?

**Comment by noahnu** [comment]
Responsibilities of a Syrupy Extension:
- Serialization: Given some python object, return a `Union[str, bytes]`.
- Assertion Diff: Given 2 non-equal serialized objects, return an iterable of formatted "diff" lines for reporting.
- Persistence: Given a python object and a test location, persist the serialized data such that it can be committed to version control.
- Recall: Given a test location, return the previously persisted serialized data.

Questions
- Regarding persistence, should it receive a python object, or the already serialized data?

**Comment by iamogbz** [comment]
@noahnu 
> Regarding persistence, should it receive a python object, or the already serialized data?

I think it should receive the python object asserted on with the assumption that the internal serializer will be called on it before persisting

I think one responsibility was missed
- Discovery: find all related snapshots in a with a location and the likely name test location that persisted the snapshot
