### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by ludaavics** [tophat/syrupy#617]
would you consider making your package available on conda?

Thanks!

**Comment by noahnu** [comment]
Yeah we can do that. I don't have much experience with conda so will have to look into what's involved.

**Comment by noahnu** [comment]
From a preliminary look, this seems more involved than I was expecting. That being said, if you are interested in opening a PR to add conda publishing to the GitHub workflow, I'll review it and connect any required credentials.

**Comment by ludaavics** [comment]
FYI i've added a [recipe](https://github.com/conda-forge/staged-recipes/pull/21360) to conda forge. 
Hopefully that'll do the trick

**Comment by noahnu** [comment]
Do you know if there's a way to maintain the recipe in this repository? Or add a test for conda to prevent regressions?

**Comment by ludaavics** [comment]
I'm making this up as a go along, but my sense is that, sure you can maintain the recipe yourself, but it probably doesn't make sense unless you really know what you're doing / have some very specific needs.

In terms of tests, you can [edit the test section](https://github.com/conda-forge/staged-recipes/pull/21360/files#diff-cd223f8bdc6f641ef5fb2a22a02b14d66d3ad12844b8b1e23ea6acdb30a95863R26) the recipe to run whatever you want. Here's the [relevant reference](https://github.com/conda-forge/staged-recipes/pull/21360/files#diff-cd223f8bdc6f641ef5fb2a22a02b14d66d3ad12844b8b1e23ea6acdb30a95863R26).

**Comment by noahnu** [comment]
I'm wondering more about how we keep the recipe up to date with versions and ensure we don't break the build process via refactoring in this repository.

Perhaps we can automate putting up a PR to the conda-forge/staged-recipes repository and trigger that on the syrupy release workflow

**Comment by ludaavics** [comment]
Agreed that would be ideal. Though, to start, it may make sense to stick with manual PR for a few releases.

**Comment by ludaavics** [comment]
@noahnu could you pls comment on the PR confirming you're OK being a maintainer of the recipe?

**Comment by noahnu** [comment]
Conda recipe added. Closing this issue. If there's a github badge we can add to the README of this repo, let's do that.

**Comment by ludaavics** [comment]
once the machine is done cranking, you should be able to add any of the badges [here](https://anaconda.org/conda-forge/syrupy/badges). Link doesn't work yet (you don't need authentication) but you can see [examples](https://anaconda.org/conda-forge/pandas/badges)
