### ISSUE TITLE
Set optional properties in ambr template?

### ISSUE THREAD

**Issue by avoidik** [tophat/syrupy#623]
**What's your question?**

Hello,

Could you please suggest is there a way to skip assertion for unimportant values in the json output based on the ambr template definitions? I have a json output similar to below where some of the values are not important for testing, but the real structure and data types are. The original json structure could be quite big for the inline `matcher=path_type` helper, I was thinking about something similar, but on the ambr template level with the callable datatypes instead of fixed values.

Sample json output

```json
{
    "abc": {
        "xyz": "unimportant"
        "jkl": "important"
    }
}
```

ambr

```
# name: DummyTest.test_test_templating[mock]
  dict({
    'abc': dict({
      'xyz': (str,),
      'jkl': 'important'
    }),
  })
# ---
```

**Comment by noahnu** [comment]
> The original json structure could be quite big for the inline matcher=path_type helper

What do you mean by this? It sounds like you are interested in the matchers. If you're worried about the matchers becoming verbose, you can create your own snapshot fixture in a conftest.py file:

```
@pytest.fixture
def fancy_snapshot(snapshot):
    return snapshot.use(matcher=path_type({r'abc\.xyz$': (str,)}, regex=True))

def test_case(fancy_snapshot):
    return dict() == fancy_snapshot
```

**Comment by avoidik** [comment]
> What do you mean by this?

I mean few kilobytes of arguments for `matcher=path_type` ...here..., it seems I need a custom ambr extension with inline matchers

```python
@pytest.fixture
def fancy_snapshot(snapshot):
    return snapshot.use(matcher=path_type(...here...}, regex=True))
```

**Comment by noahnu** [comment]
I'm not sure I understand the use case. Why would you have a few kb if arguments. Is there no pattern to the properties you want marked as "unimportant"? No single regex you can apply or data type you can filter on?

What's the source of the data you're trying to snapshot? API response? Data calculation?

**Comment by avoidik** [comment]
I'm dealing with the cloudformation templates produced by cdk, the idea here is to use syrupy to validate entire template structure without focusing too much on the properties values, while exact values of these properties I'm going to test separately
