### ISSUE TITLE
TypeError("cannot convert 'Repr' object to bytes") on failed file snapshot

### ISSUE THREAD

**Issue by JustASquid** [tophat/syrupy#624]
**Describe the bug**
`snapshot = <[TypeError("cannot convert 'Repr' object to bytes") raised in repr()] SnapshotAssertion object at 0x20ebc456220>`

**To reproduce**

```
@pytest.fixture
def snapshot(snapshot):
    return snapshot.use_extension(SingleFileSnapshotExtension)

def test_issue(snapshot):
    b = b'\x01\x01\x01\x01\x01\x00\x01\x01\x01\x01'
    assert b == snapshot
```
Run the test without creating snapshot file (or create snapshot file, and change the byte string so the assertion fails)

Interestingly, if don't use the custom fixture, and instead use `assert b == snapshot.use_extension(SingleFileSnapshotExtension)` then we don't get an error

**Expected behavior**

No exception

**Environment (please complete the following information):**

- OS: [Windows 10]
- Syrupy Version: [3.0.2]
- Python Version: [3.9]

**Comment by noahnu** [comment]
Fixed in https://github.com/tophat/syrupy/releases/tag/v4.0.0
