### ISSUE TITLE
Tests hang when diffing moderately sized binary file

### ISSUE THREAD

**Issue by JustASquid** [tophat/syrupy#625]
**Describe the bug**

Tests hang (or take an extremely long time to execute) when diffing moderately large binary files (1MB file takes 2 minutes on my system)

**To reproduce**

```
@pytest.mark.snapshot_update
def test_issue(snapshot):
    b = b'\x01' * 1000000
    assert b == snapshot.use_extension(SingleFileSnapshotExtension)
```

**Expected behavior**

The test should execute much faster

**Environment (please complete the following information):**

- OS: Windows 10
- Syrupy Version: 3.0.2
- Python Version: 3.9

**Comment by noahnu** [comment]
The next release is all about performance, so will make sure this is addressed there.

**Comment by noahnu** [comment]
Also can you compare the test time to just a plain file write?

**Comment by JustASquid** [comment]
@noahnu writing that file takes 0.001 seconds. Compared to almost 2 minutes for the diff

**Comment by noahnu** [comment]
@iamogbz this might be an interesting one to dig into
