### ISSUE TITLE
Proper way of building a wheel file from sources

### ISSUE THREAD

**Issue by jose1711** [tophat/syrupy#626]
Please what I am doing wrong here trying to build `.whl` from sources:
```
$ cd syrupy-3.0.2
$ python -m build --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (poetry-core>=1.1.0b3)
* Getting build dependencies for wheel...
* Building wheel...
Successfully built syrupy-3.0.2-py3-none-any.whl
```
No errors but the generated file is rather incomplete and contains just a single `py.typed` file:
```
$ unzip -l dist/syrupy-3.0.2-py3-none-any.whl
Archive:  dist/syrupy-3.0.2-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  1980-01-01 00:00   syrupy/py.typed
       26  2016-01-01 00:00   syrupy-3.0.2.dist-info/entry_points.txt
    10769  1980-01-01 00:00   syrupy-3.0.2.dist-info/LICENSE
       88  2016-01-01 00:00   syrupy-3.0.2.dist-info/WHEEL
    24400  2016-01-01 00:00   syrupy-3.0.2.dist-info/METADATA
      455  2016-01-01 00:00   syrupy-3.0.2.dist-info/RECORD
---------                     -------
    35738                     6 files
```
Thank you for your time.

**Comment by noahnu** [comment]
What's the reason for building from sources like this? If developing in the project, we have a pyinvoke command for building. Should be called out in the contributing guide. Some of the complexity comes from using poetry.. since setup tools added pyproject toml support, I may switch back to that.

**Comment by jose1711** [comment]
Just trying to determine why syrupy's [PKGBUILD in AUR](https://aur.archlinux.org/packages/python-syrupy) is not doing the right job (the issue was not in the source url).

**Comment by noahnu** [comment]
Oh interesting. I wasn't aware of this distribution. I can take a look in the next couple days.

**Comment by alan1world** [comment]
This line needs to be changed from
`include = ['src/syrupy/py.typed']`
to 

`include = ['src/syrupy/**/*']`

Hence only the single `py.typed'`file is appearing.  
Arch will then be able to build the whl correctly.

**Comment by noahnu** [comment]
Feel free to put up a PR, otherwise will get to this shortly.

**Comment by noahnu** [comment]
Worth noting that poetry's build seems to be working via `poetry build`. It includes the relevant files. So I imagine it's interpreting "include" differently than "build".

**Comment by noahnu** [comment]
https://python-poetry.org/docs/pyproject/#include-and-exclude

From the examples, it looks like you only need to include the "extra" files not included from the `packages` directive. Note that this "include" is under `tool.poetry` so it should be interpreted by poetry or according to poetry's spec.

**Comment by noahnu** [comment]
Does anyone know how the package was submitted to arch linux? If it was manually submitted, this would be good to add to our github workflow on continuous deployment

**Comment by carlosal1015** [comment]
Hi @noahnu the [package was updated](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-syrupy&id=a170abb5ddd81704bb9b38069d2e238dcc549811).

If want add support for Arch Linux through GitHub actions. It is possible to [follow](https://github.com/precice/ci-images/blob/master/ci-archlinux.dockerfile) [this approach](https://github.com/precice/precice/blob/develop/.github/workflows/build-and-test.yml#L70) or eventually any of Arch Users here we can make a pull request.

**Comment by noahnu** [comment]
Let's continue the discussion in #632
