### ISSUE TITLE
Partial test run snapshot update does not support pytest parametrize

### ISSUE THREAD

**Issue by iamogbz** [tophat/syrupy#63]
**Describe the bug**

When running a subset of all tests with the pytest keyword flag `-k`,  snapshots in tests matching the keyword should be updated and deleted appropriately. This does not work for `pytest.mark.parametrize` tests

**To Reproduce**
1. Checkout master
1. Remove a parametrize test case e.g.
https://github.com/tophat/syrupy/blob/7cde8a7b0773d3ecbf6b8e1a8d677ba8c982dfa2/tests/test_snapshots.py#L37
1. Run `inv test -d -u -t=<test_name>`
1. Test case does not get removed

**Expected behavior**

Test case removed from the parametrized definition gets deleted

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos catalina
 - Version: a15276c

**Additional context**
N/A

**Comment by noahnu** [comment]
This issue alongside #138 addresses https://github.com/syrusakbary/snapshottest/issues/63
