### ISSUE TITLE
Unable to pass snapshot argument to custom test class methods

### ISSUE THREAD

**Issue by behnazh-w** [tophat/syrupy#682]
**Describe the bug**

If I use a custom class that inherits from `TestCase` class, e.g.,

```python
class MyTest(TestCase):
  def test_foo(self, snapshot):
    assert bla == snapshot
```
and try to generate the snapshot, using `pytest --snapshot-update` I get the following error:
```
missing 1 required positional argument: 'snapshot'`
```
**Expected behavior**
To be able to pass `snapshot` argument to custom test class methods.

**Comment by noahnu** [comment]
This is a pytest limitation: https://docs.pytest.org/en/7.1.x/how-to/unittest.html#pytest-features-in-unittest-testcase-subclasses.

**Comment by lsmurray** [comment]
This hack worked. Maybe @noahnu can add instructions to the readme documenting that this is how users could use snapshot with unittest style test cases.

```python
class MyTest(TestCase):

  @pytest.fixture(autouse=True)
  def setupSnapshot(self, snapshot):
    self.snapshot = snapshot

  def test_foo(self, snapshot):
    assert bla == snapshot
```
