### ISSUE TITLE
having a dot in the file extension causes unexpected behavior

### ISSUE THREAD

**Issue by tolgaeren** [tophat/syrupy#703]
**Describe the bug**

Hello,

Thanks for syrupy! We ran into a small issue when customizing the file extension.

As mentioned in the title, I ran into an issue when trying to use an file extension like `png.zip`. I'm thinking, it's related to having and extra `.` in the file extension.

```console
$ pytest tests/syrupy/extensions/image/test_dot_in_extension.py --snapshot-update
=============================================================== test session starts ================================================================
platform darwin -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/tolga.eren/work/syrupy, configfile: pyproject.toml
plugins: syrupy-4.0.0, xdist-3.1.0, benchmark-4.0.0
collected 1 item                                                                                                                                   

tests/syrupy/extensions/image/test_dot_in_extension.py .                                                                                     [100%]

------------------------------------------------------------- snapshot report summary --------------------------------------------------------------
1 snapshot passed. 1 unused snapshot deleted.

Deleted test_dot_in_file_extension.png (tests/syrupy/extensions/image/__snapshots__/test_dot_in_extension/test_dot_in_file_extension.png.zip)
================================================================ 1 passed in 0.01s =================================================================
```

The unexpected part is here: 
1. Reporting says `1 snapshot passed. 1 unused snapshot deleted.`: There wasn't an unused snapshot and it wasn't deleted
2. If I run the `--snapshot--update` again, now it deletes the snapshot file, which it shoudn't.

**To reproduce**

I've modified one of the existing tests to reproduce:
```python
# tests/syrupy/extensions/image/test_dot_in_extension.py
import base64

import pytest

from syrupy.extensions.single_file import SingleFileSnapshotExtension


class DotInFileExtension(SingleFileSnapshotExtension):
    _file_extension = "png.zip"


actual_png = base64.b64decode(
    b"iVBORw0KGgoAAAANSUhEUgAAADIAAAAyBAMAAADsEZWCAAAAG1BMVEXMzMy"
    b"Wlpaqqqq3t7exsbGcnJy+vr6jo6PFxcUFpPI/AAAACXBIWXMAAA7EAAAOxA"
    b"GVKw4bAAAAQUlEQVQ4jWNgGAWjgP6ASdncAEaiAhaGiACmFhCJLsMaIiDAE"
    b"QEi0WXYEiMCOCJAJIY9KuYGTC0gknpuHwXDGwAA5fsIZw0iYWYAAAAASUVO"
    b"RK5CYII="
)


@pytest.fixture
def snapshot_dot_in_file_extension(snapshot):
    return snapshot.use_extension(DotInFileExtension)


def test_dot_in_file_extension(snapshot_dot_in_file_extension):
    assert actual_png == snapshot_dot_in_file_extension

```

Run `pytest tests/syrupy/extensions/image/test_dot_in_extension.py --snapshot-update` twice to observe the unexpected behavior.

**Expected behavior**
1. Correct reporting as in : `1 snapshot generated.`
2. and not deleting the generated snapshot in the second update run.

**Environment (please complete the following information):**

I've tested in the main branch

**Comment by noahnu** [comment]
The filename/snapshot name matching logic is all contained in https://github.com/tophat/syrupy/blob/main/src/syrupy/location.py if you wanted to dig into this to contribute. Otherwise, I'll try to prioritize getting this fixed. The test case is extremely helpful, thank you!

As an aside, this name matching logic is always a pain. There are a lot of edge cases. We have quite a number of test cases around these sorts of issues.

**Comment by tolgaeren** [comment]
Hi Noah,

I'd like to help. Let me have a look at the `location.py` to see whether I can figure out what's going on :)
