### ISSUE TITLE
Provide better default repr for classes without overridden repr

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#71]
**Describe the bug**

Snapshotting a class instance which does not explicitly define a serializable repr or str, will use the default object repr which includes the memory address of the class instance. This changes every test run.

**To Reproduce**

Add to a test file:

```
class MyClass:
    pass

def test_class(snapshot):
    assert snapshot = MyClass()
```

then

```
inv test -d -u
```

**Expected behavior**

Snapshots should not change between test runs if the code is deterministic.

**Additional context**

It's possible we don't want to try support this, as it clearly implies the data type is not meant to be serialized.

**Comment by iamogbz** [comment]
We could leave it as is, with documented instructions about overriding the `__repr__` of classes meant to be snapshotted.

**Comment by iamogbz** [comment]
I don't think this is even a bug 🐛

**Comment by noahnu** [comment]
I agree. I think adding documentation is sufficient to close out this issue.
