### ISSUE TITLE
Syrupy is recognizing snapshot as not being used (4.0.1)

### ISSUE THREAD

**Issue by abdulhaq-e** [tophat/syrupy#717]
**Describe the bug**

This is probably a regression in the latest release. I didn't observe the behavior in 4.0.0:

1. On a new test with no snapshot (using the `json` extension), I get the expected behaviour:
> 1 snapshot failed
> Snapshot 'TestFoo.test_foo' does not exist!
2. With the first `pytest --snapshot-update` (this is where the first signs of the bug is):
> 1 snapshot generated. 1 unused snapshot deleted.
Deleted TestFoo (tests/foo/__snapshots__/test_foo/TestFoo.test_foo.json)

Why does it output `Deleted ....`, that isn't the expected behaviour (the deletion doesn't happen though)
3. Another follow up when running `pytest`:
> 1 snapshot passed. 1 snapshot unused.
Re-run pytest with --snapshot-update to delete unused snapshots.

Again, that isn't correct. It gets worse though:
4. `pytest --snapshot-update`:
This time the deletion *will* happen hence the next run of `pytest` will fail since it won't find a snapshot.

# Env: 

Syrupy 4.0.1
Python 3.10

Going back to 4.0.0 solved the issue.

**Comment by abdulhaq-e** [comment]
If I have time in the weekend I will have a look at this. I can only see 1 or 2 commits that change logic in between 4.0.0 and 4.0.1

**Comment by noahnu** [comment]
https://github.com/tophat/syrupy/pull/710 is the only change in 4.0.1.
