### ISSUE TITLE
The recent release of the 'colored' package is breaking 'syrupy'

### ISSUE THREAD

**Issue by behnazh-w** [tophat/syrupy#758]
**Describe the bug**

The `colored` package that `syrupy` depends on  [has released version `1.5.0`](https://gitlab.com/dslackw/colored/-/releases/1.5.0) and it's breaking  `syrupy` with this error:

```bash 
AttributeError: module 'colored' has no attribute 'fg'
```

**Comment by noahnu** [comment]
They're not following semver? I'd expect that to be a breaking change.

Since it's just a rename, we should be able to have some interop logic support both versions for some time.

I welcome a pill request for this, otherwise will prioritize this first thing this week.

**Comment by noahnu** [comment]
It looks like colored 1.5.0 also raised the min. python version to 3.9, so it won't be easy to test here. I'll have to QA this manually unfortunately.

**Comment by behnazh-w** [comment]
> They're not following semver? I'd expect that to be a breaking change.

No, I don't think they're following semver :-(

**Comment by noahnu** [comment]
Asked for clarification on the colored repository: https://gitlab.com/dslackw/colored/-/issues/27. In the meantime, I'll release a backwards compatible fix for syrupy.

**Comment by noahnu** [comment]
The colored dependency has been removed.
