### ISSUE TITLE
Colored 1.5 broke syrupy

### ISSUE THREAD

**Issue by dfioravanti** [tophat/syrupy#764]
**Describe the bug**

I run `poetry update` this morning and it updated `colored` to 1.5. Which is a legit update according to pyrupy `pyproject.toml`. From the change log of `colored` I can see they renamed some functions like `bg`  to `back` and `fg` to `fore`. These changes broke syrupy. 

**To reproduce**

Update to colored 1.5 and try using syrupy in a CI pipeline on github/gitlab

**Expected behavior**

It should not break or it should not allow to update to 1.5

**Screenshots**

**Environment (please complete the following information):**

- OS: I am not sure whatever my CI is using, I think Alpine
- Syrupy Version: 3.0.6
- Python Version: 3.11

**Additional context**

**Comment by noahnu** [comment]
Yeah, this was an unexpected breaking change to colored on a minor version. I've released a fix on syrupy v4.

When I find some time, I might look at removing the colored dependency entirely. Our usage of it is quite simple.

**Comment by dfioravanti** [comment]
@noahnu just as a FYI, colored yanked 1.5 and renamed it 2.0. So now syrupy installs 1.4.4 which still works but it might come as a surprise to you
