### ISSUE TITLE
"exclude" filters don't appear to work correctly with msgspec structs

### ISSUE THREAD

**Issue by BenGatewood** [tophat/syrupy#784]
**Describe the bug**

When I try and exclude attributes from a custom class that inherits from [`msgspec.Struct`](https://jcristharif.com/msgspec/structs.html) the syntax/approach from the [docs](https://github.com/tophat/syrupy#exclude) doesn't seem to produce the desired behaviour and the excluded attributes remain in the snapshot

**To reproduce**

```import msgspec

from syrupy.filters import props


class Base(msgspec.Struct):
    foo: str
    bar: int


def test_base(snapshot):
    b = Base(
        foo="baz",
        bar=5,
    )

    assert b == snapshot(exclude=props("bar"))
```

**Expected behavior**

From the above example, I would expect a snapshot like: 
```# serializer version: 1
# name: test_base
  Base(foo='baz')
# ---
```

**Environment (please complete the following information):**

- OS: Mac OSX 13.5
- Syrupy Version: 4.0.8
- Python Version: 3.11

**Additional context**

Thanks for looking!

**Comment by noahnu** [comment]
Custom classes are serialized by calling `repr`, see: https://github.com/tophat/syrupy/blob/2ed84ea8e2b9dfa01cd4788f9787809ffc6b2648/src/syrupy/extensions/amber/serializer.py#L373

Since repr returns a string, we don't have a way to modify the result of calling repr to apply an exclude. You could extend the serializer to support msgspec.Struct:

```py
import pytest
from typing import Any
from syrupy.filters import props
from syrupy.extensions.amber import AmberSnapshotExtension, AmberDataSerializer

import msgspec

class MySpec(msgspec.Struct):
    a: str
    b: int


class ExtendedAmberDataSerializer(AmberDataSerializer):
    @classmethod
    def serialize_unknown(cls, data: Any, *, depth: int = 0, **kwargs: Any) -> str:
        if isinstance(data, (msgspec.Struct,)):
            return data.__class__.__name__ + super().serialize_dict(
                data=msgspec.to_builtins(data),
                **kwargs
            )[len("dict"):]
        return super().serialize_unknown(data, depth=depth, **kwargs)


class ExtendedAmberSnapshotExtension(AmberSnapshotExtension):
    serializer_class = ExtendedAmberDataSerializer


@pytest.fixture
def snapshot(snapshot):
    return snapshot.use_extension(ExtendedAmberSnapshotExtension)

def test_case(snapshot):
    assert MySpec(a="word", b=3) == snapshot(exclude=props("a"))

```

I acknowledge the serializer can be improved here.. I think we could expose an alternative to serialize_dict to handle repr a bit better

**Comment by noahnu** [comment]
Updated my example using `serialize_custom_iterable` which I've exposed in v4.1.0.

**Comment by BenGatewood** [comment]
Nice one - thanks! I'll have a go with this method for the moment

**Comment by noahnu** [comment]
Will close out this issue then. Feel free to comment and I'll re-open if there are other ways we can make this simpler.
