### ISSUE TITLE
Make serialized representation of empty iterable more concise 

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#79]
**Is your feature request related to a problem? Please describe.**

An empty list takes up 3 lines in an ambr file.

```
<class 'list'> [
]
```

**Describe the solution you'd like**

Represent an empty iterable in a more concise format:

```
<class 'list'> []
```

or

```
<class 'list'> [ ]
```

**Describe alternatives you've considered**

There's an argument that the more verbose format produces smaller git diffs if adding an element, since we don't change the line indicating a list is being used.

**Comment by iamogbz** [comment]
I think the current way is fine as it allows for a simpler diff when the list changes

**Comment by noahnu** [comment]
Marked as won't fix
