### ISSUE TITLE
Configuration option to specify default serializer plugin

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#82]
**Is your feature request related to a problem? Please describe.**

Currently you have to override the snapshot fixture in your project's root conftest.py in order to specify the default serializer class. It's potentially not clear what the final serializer is (order of shadowing).

**Describe the solution you'd like**

A configuration option to specify the python module path to load for the default serializer.

```
--snapshot-default-plugin syrupy.extensions.image.SVGImageExtension
```

**Describe alternatives you've considered**

Adding documentation for overriding the default fixture.

**Comment by msrose** [comment]
Taking this on 🎉
