### ISSUE TITLE
pytest 8 compatibility

### ISSUE THREAD

**Issue by nijel** [tophat/syrupy#845]
**Describe the bug**

[pytest 8.0.0](https://github.com/pytest-dev/pytest/releases/tag/8.0.0) has been released two days ago, is there some plan to make syrupy compatible with it?

**To reproduce**

1. `pip install pytest==8.0.0 syrupy`
2. See the error:
   
```
 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    The user requested pytest==8.0.0
    syrupy 4.6.0 depends on pytest<8.0.0 and >=7.0.0
```

**Expected behavior**

It should install.

**Screenshots**

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- Syrupy Version: 4.6.0
- Python Version: 3.11

**Additional context**

**Comment by noahnu** [comment]
I'll try have an update out this week. I'm no longer at top hat and am working on transferring project permissions over to me so I can continue development & maintenance.

**Comment by noahnu** [comment]
I have the necessary project permissions now, so will look at an update as soon as I can.
