### ISSUE TITLE
Argument conflict when trying to replace snapshottest

### ISSUE THREAD

**Issue by msrose** [tophat/syrupy#89]
**Describe the bug**

Pytest raises an error from argparse because of a conflicting arguments: both snapshottest and syrupy declare a --snapshot-update argument, so you have to trash your virtualenv or explicitly uninstall snapshottest to get syrupy working.

**To Reproduce**

1. Create a project with snapshottest and pytest as a dependency (e.g. install it in a venv)
1. Install syrupy and remove snapshottest from your dependencies
1. Running pytest shows an error because of the duplicate argument
1. Delete your virutalenv and reinstall, or explicitly uninstall snapshottest
1. pytest works a-ok

**Expected behavior**

It would be nice if you didn't get this confusing error when migrating, it would make syrupy an easier drop-in replacement for snapshottest, but it seems like this may be out of control of plugins. Could be worth calling it out explicitly in the docs for other people who encounter it, if a programmatic solution is not available.

**Desktop (please complete the following information):**

 - OS: MacOS
 - Version 10.14.5
 - Python 3.6.6, pip 18.1

**Comment by noahnu** [comment]
Syrupy is not intended to be used alongside snapshottest. We're intentionally using the `--snapshot-update` syntax from snapshottest to make the migration easier.

The recommended approach is to uninstall snapshottest, install syrupy, and run `pytest --snapshot-update`. It will automatically delete the old snapshottest snapshots.

**Comment by msrose** [comment]
Yeah I realize that, it's just confusing when you're switching, even having removed snapshottest from your codebase and dependencies, that it will have a conflict when you're trying to set up syrupy. I assumed we had removed snapshottest but since it was still lurking in the venv I got the errors, despite not using it in the project 😛

**Comment by iamogbz** [comment]
We can add documentation to help with the migration from `snapshottest`. To call out the explicit `pip uninstall snapshottest` step.
