### ISSUE TITLE
Syrupy is deleting newly created snapshots when parametrizing a class method

### ISSUE THREAD

**Issue by noahnu** [tophat/syrupy#90]
**Describe the bug**

Snapshots are being deleted immediately after being written when syrupy is run with `--snapshot-update`.

**To Reproduce**

```python
class TestMyClass:
    @pytest.mark.parametrize(
        "some_arg",
        [
            "abc",
            "def",
        ],
    )
    def test_param(self, some_arg, snapshot):
        assert some_arg == snapshot
```

**Expected behavior**

Snapshots should not be deleted if they're being used.

**Additional Context**

Syrupy v0.0.14 using the Image serializer.

**Comment by iamogbz** [comment]
This specifically happens with the `RawSingleSnapshotSerializer` should be fixed in the above
